version = 5.6.0
archive_dir = /etc/letsencrypt/archive/orbit.hmpsti.site
cert = /etc/letsencrypt/live/orbit.hmpsti.site/cert.pem
privkey = /etc/letsencrypt/live/orbit.hmpsti.site/privkey.pem
chain = /etc/letsencrypt/live/orbit.hmpsti.site/chain.pem
fullchain = /etc/letsencrypt/live/orbit.hmpsti.site/fullchain.pem
[renewalparams]
account = 43e1e1497b8833a20a483aa168b67bf7
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-07-07T10:26:32
